### ISSUE TITLE
Workspace indicator

### ISSUE THREAD

**Issue by pfr-dev** [jcs/sdorfehs#23]
I'm just piping a simple script to the bar (not using `sdorfehs-bar`) and I want to add a workspace indicator. Preferably one that shows me the total number of workspaces and the current workspace. 

I've done this on other window managers with something like this:

```
# WS
AWS="$(xprop -root '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)"
WS="$name $(expr \( $AWS + 1 \))"
NWS="$(xprop -root '\t$0' _NET_NUMBER_OF_DESKTOPS | cut -f 2)"
```
But `sdorfehs` doesn't seem to find `_NET_CURRENT_DESKTOP` 

Any hints on how I might achieve this?

(currently on NetBSD_9-STABLE)

**Comment by jcs** [comment]
Hi, this is updated now in 9cf9fca

**Comment by pfr-dev** [comment]
> Hi, this is updated now in [9cf9fca](https://github.com/jcs/sdorfehs/commit/9cf9fcad81cf4d75598cf4390b509c6198b91f51)

Champion, thanks. 

I'll probably just wait for the `sdorfehs` package to be updated in the next in the next bulk build before I test it. Once I've got it sorted I'll close this issue off. 

cheers

**Comment by pfr-dev** [comment]
It was just brought to my attention that only releases will be pulled for bulk builds. 

Any chance you'd be willing to publish a new release version?

**Comment by jcs** [comment]
Sure, I tagged a v1.2 release.

**Comment by pfr-dev** [comment]
So it would seem that `sdorfehs-1.2` on NetBSD is now a little broken. 

Version 1.2 is now packaged so it was upgraded using `pkgin` 

The best way to explain what I mean it to post screenshots:

(1) This is how it looked before the upgrade:

![root 18-11-2021 21:59](https://user-images.githubusercontent.com/776010/142757617-060ad442-0899-4c3a-9448-74da8daa87df.png)

(2) This is what it looks like on 1.2:

![root 18-11-2021 21:51](https://user-images.githubusercontent.com/776010/142757641-b1cacb05-abe4-467f-a9e6-304fae821d67.png)

As you can see, the gaps are larger in the center between windows but nonexistent on the outside borders. Also note that I took the second scrot after toggling the bar off. After the bar is toggled off it still remains while the windows are stretched as if the bar isn't there. 

I've used this script that you gave me some time ago to toggle the bar on and off:

```
#!/bin/sh

STICKY=`sdorfehs -c "set barsticky"`

if [ "$STICKY" = "1" ]; then
    STICKY=0
else
    STICKY=1
fi

sdorfehs -c "set barsticky ${STICKY}"
```

For good measure, here is my `~/.config/sdorfehs/config`:

```
# s = win/super key
# M = meta/alt key
# C = control/ctrl key

# general settings
set padding 0 0 0 0
set vscreens 9
set gap 9
set ignoreresizehints 1
set onlyborder 0
set border 0
set font InputMonoCondensed:style=Regular:pixelsize=14:antialias=true
set fgcolor #C0C5CE
set bgcolor #2d2d2d
set fwcolor #757575
set bwcolor #757575

# bar settings
set barbordercolor #444444
set barpadding 5 1
set barborder 0
set bargravity nw
set barinpadding 0
set barsticky 1

# call bar toggle script
definekey top s-t exec sh $HOME/.scripts/bartoggle.sh

# frame splits
bind S split
bind s hsplit

# no prefix
definekey top s-M-Return exec xterm
definekey top s-Return exec xst
definekey top s-b exec intel_backlight 20

# dmenu/passmenu
definekey top s-d exec $HOME/.scripts/dmenu_run.sh
definekey top s-p exec $HOME/.scripts/passmenu_run.sh
definekey top s-s exec $HOME/.scripts/dmenu_scrot.sh
definekey top s-r exec $HOME/.scripts/ocr.sh
definekey top s-c exec $HOME/.scripts/colorpicker.sh

# volume keys
definekey top XF86AudioRaiseVolume exec mixerctl -w outputs.master+=12
definekey top XF86AudioLowerVolume exec mixerctl -w outputs.master-=12
definekey top XF86AudioMute exec mixerctl -w outputs.master3.mute++

# quit sdorfehs
bind Delete exec killall sdorfehs

# lock screen
definekey top s-M-l exec slock
#bind L exec slock

# prevent accidental closes
unbind k

# swap workspaces, but define it in 'top' to avoid having to prefix with C-a
definekey top M-1 vselect 0
definekey top M-2 vselect 1
definekey top M-3 vselect 2
definekey top M-4 vselect 3
definekey top M-5 vselect 4
definekey top M-6 vselect 5
definekey top M-7 vselect 6
definekey top M-8 vselect 7
definekey top M-9 vselect 8
definekey top M-0 vselect 9

# move windows to diferent workspaces
definekey top C-1 vmove 0
definekey top C-2 vmove 1
definekey top C-3 vmove 2
definekey top C-4 vmove 3
definekey top C-5 vmove 4
definekey top C-6 vmove 5
definekey top C-7 vmove 6
definekey top C-8 vmove 7
definekey top C-9 vmove 8
definekey top C-0 vmove 9

# act normal but prevent firefox raising itself when links are opened from
# other apps
set rudeness 12

# let popups stay centred
unmanage xmessage
unmanage xprompt
ummanage sxiv
unmanage mpv

# startup configureation
# exec other statup apps here
#exec ruby $HOME/.config/sdorfehs/sdorfehs-bar.rb
exec sh $HOME/.config/sdorfehs/barscript.sh
```

**Comment by jcs** [comment]
The gap setting no longer affects the outer edges, so you'll have to increase your `padding` setting.

**Comment by pfr-dev** [comment]
> The gap setting no longer affects the outer edges, so you'll have to increase your `padding` setting.

Ok, but padding also affects the bar. Can I get the same layout as before or is that no longer possible? 

It also appears `set onlyborder 0` no longer eliminates the border when there is only one frame. It this correct?

**Comment by jcs** [comment]
`set barinpadding 1`

**Comment by pfr-dev** [comment]
> `set barinpadding 1`

Lovely. So only remaining issues are `set onlyboarder 0` no longer maximises a single frame and the phantom bar that remains after asking it to disappear.

**Comment by pfr-dev** [comment]
Also with relation to the original issue `_NET_CURRENT_DESKTOP` 

```
$ AWS="$(xprop -root '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)"
$ WS="$name $(expr \( $AWS + 1 \))"
$ NWS="$(xprop -root '\t$0' _NET_NUMBER_OF_DESKTOPS | cut -f 2)
$ echo $WS
$ 2                   # this is correct
$ echo $NWS
$ 12                 # this is incorrect - I have 9 workspaces
$ # move window to workspace 6
$ echo $WS
$ 2                   # still echoing the workspace it originated on
```

This still

**Comment by jcs** [comment]
I'm not sure if `onlyborder 0` should eliminate the padding, I'll need to think about that and maybe add another setting or another value to `onlyborder`.

I can't reproduce the `_NET_CURRENT_DESKTOP` not updating, are you sure that is re-running `xprop`?

The incorrect `_NET_NUMBER_OF_DESKTOPS` value should be fixed in 8533cd0.

**Comment by pfr-dev** [comment]
> I'm not sure if `onlyborder 0` should eliminate the padding, I'll need to think about that and maybe add another setting or another value to `onlyborder`.

That is a good idea and would come in handy!

> I can't reproduce the `_NET_CURRENT_DESKTOP` not updating, are you sure that is re-running `xprop`?
> The incorrect `_NET_NUMBER_OF_DESKTOPS` value should be fixed in [8533cd0](https://github.com/jcs/sdorfehs/commit/8533cd06d402f01f11b77fa64af722a516948f35).

Thanks. It is now detecting the correct number of workspaces. `_NET_CURRENT_DESKTOP` does update, it just isn't re-running the `xprop` command when I try to `echo $WS`. Running the full command it does reflect the correct workspace (see screenshot). However, I still cannot get any of this output in the bar. See my barscript below the screenshot. 

![2021-11-23_@_22-14-32-scrot](https://user-images.githubusercontent.com/776010/143014919-fbab1f96-35b2-4299-885b-ccbd0f08fb7f.png)

`barscript.sh`
```
#!/bin/sh

set -eu
while :
do
        # Uptime
        UP=$(uptime)
        UP=${UP#*up}
        UP=${UP%%,*}

        # Packages
        PKGS=$(pkg_info | wc -l)
        PKGS=${PKGS##* }                # strip leading spaces

    # Workspace
    AWS="$(xprop -root '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)"
    WS="$name $(expr \( $AWS + 1 \))"
    NWS="$(xprop -root '\t$0' _NET_NUMBER_OF_DESKTOPS | cut -f 2)"

        # Volume
        VOL=$(mixerctl -n outputs.master)
        VOL=${VOL%,*}                   # strip other channel
        VOL=$(( (VOL * 100) / 254 ))
        MUTE=$(mixerctl -n outputs.master3.mute)
        if [ $MUTE = on ]
        then    MUTE="[ ^fg(red)Shhh!^fg() ]"
        else    MUTE=""
        fi

        # Battery
        O=$(envstat -s 'acpibat0:charge,acpibat0:charging,acpibat0:discharge rate')
        BAT_PERC=${O#*(}                # strip from beginning to '('
        BAT_PERC=${BAT_PERC%%.*}        # strip from first '.' to end
        BAT_STATE=${O#*charging:}       # snag charge state

        if [ $BAT_STATE = TRUE ]
        then STATE="^fg(green)+^fg()"   # charging
        else STATE="^fg(red)-^fg()"     # discharging
        fi

        # Date
        D=$(date '+%a %d %b %I:%M')

        # Weather
        WTTR=$(cat $HOME/.scripts/weather.txt)

        # Moon phase
        MOON="$(cat $HOME/.scripts/moon.txt)"

        # Print
        echo "$D ~ $WTTR [ $PKGS# ][ $VOL% ]$MUTE[ $STATE$BAT_PERC% ][$WS|$NWS]" > ~/.config/sdorfehs/bar
        sleep 1
done
```

**Comment by 0323pin** [comment]
Hi guys,

NetBSD package maintainer here, I thought I'd join the party here, as it's probably better than keeping discussions going on in different places.

Are you ok with it?
If so, let's try to get this sorted.

@pfr-dev can you please provide the full file you are using to get the info into the bar?

It seems that, on the section you are showing,

```
$ AWS="$(xprop -root '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)"
$ WS="$name $(expr \( $AWS + 1 \))"
$ NWS="$(xprop -root '\t$0' _NET_NUMBER_OF_DESKTOPS | cut -f 2)
```

WS is being calculated using the older AWS, hence not changing when you actually change workspaces.

Are you actually refreshing AWS before re-calculating WS?

**Comment by pfr-dev** [comment]
> @pfr-dev can you please provide the full file you are using to get the info into the bar?

Here is my full `barscript.sh`
```#!/bin/sh

set -eu
while :
do
	# Uptime
	UP=$(uptime)
	UP=${UP#*up}
	UP=${UP%%,*}

	# Packages
	PKGS=$(pkg_info | wc -l)
	PKGS=${PKGS##* }		# strip leading spaces

    # Workspace
    AWS="$(xprop -root '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)"
    WS="$name$(expr \( $AWS + 1 \))"        # because workspaces begin at '0'
    NWS="$(xprop -root '\t$0' _NET_NUMBER_OF_DESKTOPS | cut -f 2)"

	# Volume
	VOL=$(mixerctl -n outputs.master)
	VOL=${VOL%,*}			# strip other channel
	VOL=$(( (VOL * 100) / 254 ))
	MUTE=$(mixerctl -n outputs.master3.mute)
	if [ $MUTE = on ]
	then	MUTE=" ^fg(red)Shhh!^fg() /"
	else	MUTE=""
	fi

	# Battery
	O=$(envstat -s 'acpibat0:charge,acpibat0:charging,acpibat0:discharge rate')
	BAT_PERC=${O#*(}        # strip from beginning to '('
	BAT_PERC=${BAT_PERC%%.*}        # strip from first '.' to end
	BAT_STATE=${O#*charging:}       # snag charge state

	if [ $BAT_STATE = TRUE ]
	then STATE="^fg(green)+^fg()"       # charging
	else STATE="^fg(red)-^fg()"     # discharging
	fi

	# Date
	D=$(date '+%a %d %b %I:%M')

	# Weather
	WTTR=$(cat $HOME/.scripts/weather.txt)

	# Moon phase
	MOON="$(cat $HOME/.scripts/moon.txt)"

	# Print
    echo "$D ~ $WTTR / $PKGS# / $VOL% /$MUTE $STATE$BAT_PERC% / [$WS-$NWS]" > ~/.config/sdorfehs/bar
	sleep 1
done
```

**Comment by 0323pin** [comment]
@pfr-dev let's say you install a few more packages on your system. Does the package count get updated?
Does your battery charge gets updated?

> what I've learned is that only after re-calculating both AWS & WS does it return the correct workspace number.

Exactly, you are calculating the value of a variable and feeding the result to calculate a second variable. To update the second variable, you obviously need to calculate the first variable again.

Sorry for my ignorance but,

```
#!/bin/sh

set -eu
while :
do

...

sleep 1
done
```

What does this do? I mean `set -eu`?

I would do it like the following,

```
#!/bin/sh

while true; do

...

sleep 2
done
exit 0
```

What happens if you do it like this?

Now, I need to change laptop just watch your youtube (!) video :(
(just joking but, I can't watch youtube crap on my browser).

**Comment by pfr-dev** [comment]
> let's say you install a few more packages on your system. Does the package count get updated?
> Does your battery charge gets updated?

Yes, everything else in the bar is working (battery/packages/volume/weather etc).


> What does this do? I mean `set -eu`?

I actually dont know. I think this was in the example script I'm pretty sure. I'll try your suggestion and let you know. 


> I can't watch youtube crap on my browser

Just install the dependencies and delete them afterwards 🤣

**Comment by pfr-dev** [comment]
So, just to recap:
- workapsce indicator now working 👍 
- Just need to figure out what is going on with the `barsticky` toggle
- and hopefully, add another value to `onlyborder` to overide padding etc.

**Comment by DN-debug** [comment]
Hi @0323pin I'm the * uninvited guest to this party * 

> ```
> #!/bin/sh
> 
> set -eu
> while :
> do
> 
> ...
> 
> sleep 1
> done
> ```
> 
> What does this do? I mean `set -eu`?

set allows you to add values to shell options and tells it what to do with the names/variables/parameters

Since this is a bash script, in a layman's term, when you use -e, the script is interpreted once, **if any errors are encountered** then it goes [ back to the position where it is defined ] to the top, and tells the script to exit, basically saying "Buddy I can't do this, lets quit".

In case of variables, if any variable is not defined/set before being called/referenced, then **-u** will also exit the script.

> 
> I would do it like the following,
> 
> ```
> #!/bin/sh
> 
> while true; do
> 
> ...
> 
> sleep 2
> done
> exit 0
> ```
> 
> What happens if you do it like this?
> 

Nothing much, it just dumps the output of all variables/names/parameters and whatnot. If you want to see what failed, then use set -x to debug.

**Comment by 0323pin** [comment]
@DN-debug thanks for chiming in and explain some shell script basics. I've so far invested too litle time learning these sort of things and have mainly focused on packaging software.

But, ...

> Nothing much, it just dumps the output of all variables/names/parameters and whatnot.

Which is what we want here. Or, am I wrong? To refresh the workspace number we need to dump the old value and re-calculate it.

The goal haa been achived for @pfr-dev but, the dumb shell scripter in me still needs to understand why the original script is not dropping the AWS variable and re-calculating it, while the change I've suggest does.

Thanks

**Comment by DN-debug** [comment]
> @DN-debug thanks for chiming in and explain some shell script basics. I've so far invested too litle time learning these sort of things and have mainly focused on packaging software.
> 
> But, ...
> 
> > Nothing much, it just dumps the output of all variables/names/parameters and whatnot.
> 
> Which is what we want here. Or, am I wrong? To refresh the workspace number we need to dump the old value and re-calculate it.
> 
> The goal haa been achived for @pfr-dev (see his EDIT above) but, the dumb shell scripter in me still needs to understand why the original script is not dropping the AWS variable and re-calculating it, while the change I've suggest does.
> 
> Thanks

By "dumps all the output" I meant "errors/warnings" .

The "while-loop" should continue from the start after "sleep 1" [interval] down in the bottom of the script.

I copied the workspace bit from his script to test on my system just now and it works for me. 

I only removed the **$name** variable as it is throwing unbound error for me, which I suspect is because it is not defined anywhere in the script resulting in `set -u` throwing the unbound error. [ another reason why you should specify 'set' helpers to catch exceptions and errors ]

`line 17: name: unbound variable`

I'd like to know which shell you are using, if anything other than Bash then did you specify 'she-bang' in your script? Are you seeing any errors while running testing the script file?

I have used your approach of defining while-loop as well, both the approaches (yours and Dave's ) is going to result the same.

**Comment by 0323pin** [comment]
@DN-debug 
> The "while-loop" should continue from the start after "sleep 1" [interval] down in the bottom of the script.

Yeah, this much I know, this is the way I usually do it.

> [ another reason why you should specify 'set' helpers to catch exceptions and errors ]

It's not my script, rather @pfr-dev but, I've learned something, so thanks.

The rest is a question for @pfr-dev but, I believe he is using `ksh`.

As said, I used to do it through while-loops but, I'm not using any bar/panel these days and I'm on `nushell`.

**Comment by DN-debug** [comment]
> @DN-debug
> 
> 
> The rest is a question for @pfr-dev but, I believe he is using `ksh`.
> 
> As said, I used to do it through while-loops but, I'm not using any bar/panel these days and I'm on `nushell`.

My bad, sorry if I wasn't clear enough :sweat_smile: . It's already working for him, since you used his script to test and it didn't work so that's why I asked you for the output and shebang. 

Either ways, you'll have to use the syntax supported in your nushell. I use Fish but I converted the syntax to Bash to test it out, as below:


```

#/bin/bash

set -eu
while :
do

   # Workspace 
   # I have removed the leading $ used to define the variable in original script
   # also removed the $name, as it is not needed in my case.

    AWS="$(xprop -root '\t$0' _NET_CURRENT_DESKTOP | cut -f 2)"
    WS=" $(expr \( $AWS + 1 \))" 
    NWS="$(xprop -root '\t$0' _NET_NUMBER_OF_DESKTOPS | cut -f 2)"


	# Date
	D=$(date '+%a %d %b %I:%M')


	# Print
        # only using the number for current desktop
        echo  "$D  /  $WS" > ~/.config/sdorfehs/bar
	sleep 1

done
```

Hope it helps in someway if you decide to use the sdorfehs bar. :smiley:

**Comment by 0323pin** [comment]
@DN-debug Yes, you have been really helpful, thanks.

Maybe these are really basic things but, I've learned a few things today, appreciated. I've told Dave to comeback here and have a look.

**Comment by pfr-dev** [comment]
@DN-debug  thank you for this. 

I knew it was **$name** that was the issue because I was getting `sh: name: parameter not set`
I could have sworn that I tried removing it but alas, it works now _with_ `set -eu` at the beginning of the script. 
final result is:
```
#!/bin/sh

set -eu
while :
do
...
sleep 1
done
```
